version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
      args:
        PUBLIC_URL: /
    ports:
      - 3000:3000
    volumes:
      - ./:/oh
    depends_on:
      - backend
    networks:
      - openhospital
  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
      args:
        GITHUB_ORG: intesys
        OH_CORE_BRANCH: staging3
        OH_API_BRANCH: staging3
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - openhospital

  database:
    build:
      context: ./docker
      dockerfile: Dockerfile.database
      args:
        GITHUB_ORG: intesys
        OH_CORE_BRANCH: staging3
    ports:
      - "3306:3306"
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1
    networks:
      - openhospital

networks:
  openhospital:
